run:
  timeout: 5m
  go: "1.22"
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt
    - gocritic
    - misspell
    - revive

linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - style
      - diagnostic
    disabled-checks:
      - whyNoLint  # we don't require justification for nolint directives in this repo
  revive:
    rules:
      - name: var-naming
      - name: indent-error-flow
      - name: errorf
      - name: blank-imports

issues:
  exclude-dirs:
    - vendor
    - testdata
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - revive
  max-issues-per-linter: 0
  max-same-issues: 0
